version: '3.7'

networks:
  zippy:

services:
  api:
    image: ${DOCKER_REGISTRY}/zippy-api:$DOCKER_TAG
    build:
      context: ./api
      target: zippy-api
    networks:
      - zippy
    environment:
      - APP_ENV
      - DATABASE_URL
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - TRUSTED_PROXIES
      - CLIENT_ID
      - CLIENT_SECRET
    volumes:
      - zippy_vol:/data
    depends_on:
      - rabbitmq
    ports:
      - ${ZIPPY_API_PORT}:80

  worker:
    image: ${DOCKER_REGISTRY}/zippy-worker:$DOCKER_TAG
    build:
      context: ./api
      target: zippy-worker
    networks:
      - zippy
    depends_on:
      - rabbitmq
    environment:
      - APP_ENV
      - DATABASE_URL
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - VERIFY_SSL
    volumes:
      - zippy_vol:/data

  cron:
    image: ${DOCKER_REGISTRY}/zippy-worker:$DOCKER_TAG
    build:
      context: ./api
      target: zippy-worker
    command: ['/srv/app/docker/cron/start-cron.sh']
    networks:
      - zippy
    depends_on:
      - rabbitmq
    environment:
      - APP_ENV
      - DATABASE_URL
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - VERIFY_SSL

  rabbitmq:
    image: rabbitmq:3.7.14-management
    hostname: rabbitmq
    networks:
      - zippy
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq

volumes:
  rabbitmq_vol:
  zippy_vol:
