image:
  registry: alchemyfr
  tag: latest

fullnameOverride:
nameOverride:

nodeSelector: {}

rabbitmq:
  enabled: true
  username: zippy
  password: define-me
  # Define host only if rabbitmq service is disabled
  host:
  port: 5672
  vhost: /
  nodeName: zippy@rabbitmq
  epmdPort: 55950
  erlangCookie: 'nUhtWhdRmqbhnEYIiwlC'
  setupVhost: true
  externalSecretName:
  externalSecretMap:
    username: RABBITMQ_USER
    password: RABBITMQ_PASSWORD
  ssl: false
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    size: 1Gi
    subPath:

zippy:
  # You should defined restricted IP.
  # or (/!\ insecured) '127.0.0.1,REMOTE_ADDR' to allow all proxies
  trustedProxies: '127.0.0.1,REMOTE_ADDR'
  database:
    # i.e. postgres://user@pass:port/db-name
    dsn:
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 5Gi

  maxExpirationTime: -1

  storage:
    serveOnS3: false

  client:
    id: client
    secret: secret

  worker:
    replicas: 1

ingress:
  enabled: true
  secretName:
  hostname:
  annotations:
  extraLabels:
