{{- with .Values.ingress }}
{{- if .enabled }}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "zippy.fullname" $ }}-ingress
{{- if .ingress.annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
{{- if .ingress.extraLabels }}
  labels:
{{ toYaml .extraLabels | indent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ required "Missing ingress.hostname" .hostname | quote }}
      http:
        paths:
          - path: /
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "zippy.fullname" $ }}-api
                port:
                  number: 80
            {{- else }}
            backend:
              serviceName: {{ include "zippy.fullname" $ }}-api
              servicePort: 80
            {{- end }}
  tls:
    - hosts:
        - {{ required "Missing ingress.hostname" .hostname }}
      secretName: {{ .secretName | quote }}
{{- end }}
{{- end }}
