{{- with .Values.rabbitmq }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zippy.fullname" $ }}-rabbitmq-config
data:
  {{- if .erlangCookie }}
  RABBITMQ_NODENAME: "{{ .username }}@{{ .host | default (printf "%s-rabbitmq" (include "zippy.fullname" $)) }}"
  RABBITMQ_ERLANG_COOKIE: {{ .erlangCookie | quote }}
  ERL_EPMD_PORT: {{ .epmdPort | quote }}
  {{- end }}
{{- end }}
