{{- with .Values.rabbitmq }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zippy.fullname" $ }}-rabbitmq-config
data:
  RABBITMQ_NODENAME: {{ .nodeName | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .erlangCookie | quote }}
  ERL_EPMD_PORT: {{ .epmdPort | quote }}
{{- end }}
