{{ $jobName := "rabbitmq-vhost-setup" }}
{{- with .Values.rabbitmq }}
{{- if .setupVhost }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zippy.fullname" $ }}-{{ $jobName }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.14-management
        args:
          - |
            #!/bin/sh
            set -ex
            n=0
            until [ "$n" -ge 20 ]; do
            rabbitmqctl -n {{ .nodeName }} await_startup && break
            n=$((n+1))
            sleep 5
            done
        
            rabbitmqctl -n ${{ .nodeName }} await_startup
            rabbitmqctl -n {{ .nodeName }} add_vhost {{ .vhost | quote }}
            rabbitmqctl -n {{ .nodeName }} set_permissions -p {{ .vhost | quote }} ${RABBITMQ_USER} '.*' '.*' '.*'
        env:
        {{- include "zippy.rabbitmqCredentials" $ | indent 8 }}
        envFrom:
        - secretRef:
            name: {{ include "zippy.fullname" $ }}-rabbitmq
        - configMapRef:
            name: {{ include "zippy.fullname" $ }}-rabbitmq-config
      restartPolicy: Never
  backoffLimit: 10
{{- end }}
{{- end }}
