{{ with .Values.zippy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zippy.fullname" $ }}-worker
spec:
  replicas: {{ .worker.replicas }}
  selector:
    matchLabels:
      app: zippy
      tier: worker
  template:
    metadata:
      labels:
        app: zippy
        tier: worker
    spec:
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .persistence.existingClaim | default (printf "%s-data-pvc" (include "zippy.fullname" $)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
      - name: zippy-worker
        image: {{ $.Values.image.registry }}/zippy-worker:{{ $.Values.image.tag }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - name: data
            mountPath: "/data"
        env:
          {{- include "zippy.rabbitmqCredentials" $ | indent 10 }}
        envFrom:
          - secretRef:
              name: {{ include "zippy.fullname" $ }}-rabbitmq
          - secretRef:
              name: {{ include "zippy.fullname" $ }}-db-secret
{{- end }}
